---
header:
  license:
    content: |
      SPDX-License-Identifier: (MIT OR Apache-2.0)
      Copyright Authors of bpfd
  paths:
    - bpfd
    - bpfd-common
  paths-ignore:
    - 'bpfd/src/bpf'
    - '**/target/**'
    - '**/*.toml'
    - '**/*.proto'
    - '**/*.lock'
    - '**/*.yml'
    - '**/*.md'

  comment: on-failure
