---
extends: default
rules:
  line-length: disable
  document-start: disable
  comments:
    min-spaces-from-content: 1
ignore:
  - libbpf/*
  - vendor/*
  - bpfd-operator/config/crd/*
  - bpfd-operator/config/rbac/*
  ## Kustomize automatically formats these incorrectly
  - bpfd-operator/config/bpfd-deployment/kustomization.yaml
  - bpfd-operator/config/bpfd-operator-deployment/kustomization.yaml
