[workspace]
members = ["bpfd", "bpfd-api", "bpfd-common", "bpfctl", "xtask", "tests/integration-test", "tests/integration-test-macros"]

[patch.crates-io]
aya = { git = "https://github.com/dave-tucker/aya", branch="program-from-pinned" }
oci-distribution = {git = "https://github.com/krustlet/oci-distribution", branch="main"}