[workspace]
members = ["bpfd", "bpfd-common", "xtask"]

[patch.crates-io]
aya = {git = "https://github.com/dave-tucker/aya", branch="bpfd-v2"}
[patch."https://github.com/aya-rs/aya"]
aya = {git = "https://github.com/dave-tucker/aya", branch="bpfd-v2"}
