consolidate-commits = true
consolidate-pushes = true
dev-version = true
dev-version-ext = "dev"
post-release-commit-message = "bpfd, bpfd-common: start next development iteration {{next_version}}"
pre-release-commit-message = "bpfd, bpfd-common: release version {{version}}"
shared-version = true
