pre-release-commit-message = "bpfd, bpfd-common: release version {{version}}"
post-release-commit-message = "bpfd, bpfd-common: start next development iteration {{next_version}}"
consolidate-pushes = true
consolidate-commits = true
shared-version = true
dev-version = true
dev-version-ext = "dev"
