---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: bpfd-agent-role
rules:
- apiGroups:
  - bpfd.io
  resources:
  - bpfprogramconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfd.io
  resources:
  - bpfprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfd.io
  resources:
  - bpfprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfd.io
  resources:
  - bpfprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
