[package]
name = "bpfd"
version = "0.1.0"
edition = "2021"

[[bin]]
    name = "bpfd"
    path = "src/server.rs"

[[bin]]
    name = "bpfctl"
    path = "src/client.rs"

[dependencies]
tonic = "0.6"
prost = "0.9"
thiserror = "1"
structopt = "0.3"
aya = { git = "https://github.com/dave-tucker/aya", branch = "ext" }
tokio = { version = "1.14.0", features = ["full"] }
uuid = { version = "0.8", features = ["v4"] }
log = "0.4"
env_logger = "0.9"
libc = "0.2"

[build-dependencies]
tonic-build = "0.6"
