# permissions for end users to view ebpfprograms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ebpfprogram-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/part-of: bpfd-operator
    app.kubernetes.io/managed-by: kustomize
  name: ebpfprogram-viewer-role
rules:
- apiGroups:
  - bpfd.io
  resources:
  - ebpfprograms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfd.io
  resources:
  - ebpfprograms/status
  verbs:
  - get
