[package]
description = "gRPC bindings to the CSI spec"
edition = "2021"
license = "Apache-2.0"
name = "bpfd-csi"
repository = "https://github.com/bpfd-dev/bpfd"
version = "1.8.0"

[dependencies]
prost = { workspace = true, features = ["prost-derive", "std"] }
prost-types = { workspace = true }
tonic = { workspace = true, features = ["codegen", "prost", "tls"] }
