---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bpfd-cert-cluster-issuer
  namespace: kube-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bpfd-ca
  namespace: kube-system
spec:
  isCA: true
  commonName: bpfd-ca
  secretName: bpfd-ca
  privateKey:
    algorithm: RSA
  issuerRef:
    name: bpfd-cert-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1                             
kind: Issuer                             
metadata:                               
  name: bpfd-cert-issuer
  namespace: kube-system                          
spec:
  ca:
    secretName: bpfd-ca