---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: bpfd-sa
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: bpfd-agent-role
  namespace: kube-system 
rules: 
- apiGroups: ["bpfd.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bpfd-agent-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bpfd-agent-role
subjects:
- kind: ServiceAccount
  name: bpfd-sa
  namespace: kube-system
