[tls] # REQUIRED
ca_cert = "/etc/bpfd/certs/ca/ca.pem"
cert = "/etc/bpfd/certs/bpfd/bpfd.pem"
client_cert = "/etc/bpfd/certs/bpfd-client/bpfd-client.pem"
client_key = "/etc/bpfd/certs/bpfd-client/bpfd-client.key"
key = "/etc/bpfd/certs/bpfd/bpfd.key"

[interfaces]
[interface.eth0]
xdp_mode = "hw" # Valid xdp modes are "hw", "skb" and "drv". Default: "skb".

[[grpc.endpoints]]
address = "::1"
enabled = true
port = 50051
type = "tcp"

[[grpc.endpoints]]
enabled = false
path = "/run/bpfd/bpfd.sock"
type = "unix"
