---
apiVersion: v1
kind: ConfigMap
metadata:
  name: go-tc-counter-config
  namespace: kube-system
data:
  go-tc-counter.toml: |
    [tls]
      ca_cert = "/etc/bpfd/certs/ca/ca.crt"
      cert = "/etc/bpfd/certs/bpfd-client/tls.crt"
      key = "/etc/bpfd/certs/bpfd-client/tls.key"
    [config]
      interface = "ens3"
      direction = "ingress"
      bytecode_uuid = "62c2a443-9beb-4261-9c46-33a29612643d"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: go-tc-counter-cert
  namespace: kube-system
spec:
  dnsNames:
    - localhost
  ipAddresses:
    - 127.0.0.1
  commonName: go-tc-counter
  secretName: go-tc-counter-cert-secret
  privateKey:
    algorithm: RSA
  issuerRef:
    name: bpfd-cert-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: v1
kind: Pod
metadata:
  name: go-tc-counter-pod
  namespace: kube-system
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  terminationGracePeriodSeconds: 15
  nodeSelector:
    kubernetes.io/hostname: ebpf-k8s-2
  containers:
  - name: go-tc-counter
    image: quay.io/$USER/go-tc-counter:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    volumeMounts:
    - name: go-tc-counter-cert
      mountPath: /etc/bpfd/certs/bpfd-client
      readOnly: true
    - name: bpfd-ca
      mountPath: /etc/bpfd/certs/ca
      readOnly: true
    - name: host-bytecode
      mountPath: /run/bpfd/bytecode
      readOnly: false
    - name: go-tc-counter-maps
      mountPath: /run/bpfd/fs/maps
      readOnly: true
    - name: go-tc-counter-config
      mountPath: /etc/bpfd/go-tc-counter.toml
      subPath: go-tc-counter.toml
      readOnly: true
  volumes:
  - name: go-tc-counter-cert
    secret:
      secretName: go-tc-counter-cert-secret
      optional: false
  - name: bpfd-ca
    secret:
      secretName: bpfd-ca
      optional: false
  - name: host-bytecode
    hostPath:
      path: /run/bpfd/bytecode
  - name: go-tc-counter-maps
    hostPath:
      path: /run/bpfd/fs/maps
  - name: go-tc-counter-config
    configMap:
      name: go-tc-counter-config
