apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: kube-system
data:
  ## Can be configured at runtime
  bpfd.agent.image: quay.io/bpfd/bpfd-agent:latest
  bpfd.image: quay.io/bpfd/bpfd:latest
  bpfd.log.level: "info"
