name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rust-src

      - uses: Swatinem/rust-cache@v1

      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get install -qy libelf-dev llvm-12-tools
          cargo install bpf-linker

      - name: Build eBPF
        run: |
          cargo xtask build-ebpf
          pushd bpfd-ebpf
          make
          popd

      - name: Check formatting
        run: |
          cargo fmt --all -- --check
          pushd bpfd-ebpf
          cargo fmt --all -- --check
          popd

      - name: Run clippy
        run: |
          cargo clippy --all -- -A clippy::derive_partial_eq_without_eq --deny warnings
          pushd bpfd-ebpf
          cargo clippy --all -- -A clippy::derive_partial_eq_without_eq --deny warnings
          popd

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: RUST_BACKTRACE=full cargo test --verbose
