name: build-bpf

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Install deps
        run: apt-get update && apt-get install -qy libelf-dev

      - name: Build
        run: cargo build --manifest-path bpfd-ebpf/Cargo.toml --verbose

      - name: Run tests
        run: RUST_BACKTRACE=full cargo test --manifest-path bpfd-ebpf/Cargo.toml --verbose
