name: license

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  check-license:
    name: Check License
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3
      - name: Check License Header
        uses: apache/skywalking-eyes@f461a46e74e5fa22e9f9599a355ab4f0ac265469
