name: lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy, miri
          override: true

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -qy libelf-dev libc6-dev

      - name: Check formatting
        run: |
          cargo fmt --all -- --check
          pushd bpfd-ebpf
          cargo fmt --all -- --check
          popd

      - name: Run clippy
        run: |
          cargo clippy --all -- -A clippy::derive_partial_eq_without_eq --deny warnings
          pushd bpfd-ebpf
          cargo clippy --all -- -A clippy::derive_partial_eq_without_eq --deny warnings
          popd
