apiVersion: bpfd.io/v1alpha1
kind: EbpfProgramConfig
metadata:
  labels:
    app.kubernetes.io/name: ebpfprogramconfig
    app.kubernetes.io/instance: ebpfprogramconfig-sample
    app.kubernetes.io/part-of: bpfd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: bpfd-operator
  name: ebpfprogramconfig-sample
spec:
  # TODO(user): Add fields here
