apiVersion: bpfd.io/v1alpha1
kind: EbpfProgramConfig
metadata:
  labels:
    app.kubernetes.io/name: ebpfprogramconfig
  name: xdp-pass-all-nodes
  finalizers: 
  - ebpfprogram.bpfd.io/finalizer
spec:
  ## Must correspond to image section name
  name: pass
  type: XDP
  # Select all nodes
  nodeselector: 
    matchLabels: 
      run.ebpf: "true" 
  priority: 0
  attachpoint: 
    interface: eno1
  bytecode:
    imageurl: quay.io/bpfd/bytecode:xdp_pass
