apiVersion: bpfd.io/v1alpha1
kind: EbpfProgramConfig
metadata:
  labels:
    app.kubernetes.io/name: ebpfprogramconfig
  name: xdp-pass-all-nodes
spec:
  ## Must correspond to image section name
  name: pass
  type: XDP
  # Select all nodes
  nodeselector: {}
  priority: 0
  attachpoint: 
    interface: eth0
  bytecode:
    imageurl: quay.io/bpfd/bytecode:xdp_pass
